### ISSUE TITLE
Module huectl.ro is missing

### ISSUE THREAD

**Issue by p-f** [mechalas/hue-control#2]
Hi!

I wanted to try this out, but there's one module called `huectl.ro` missing.

I tried running `huemgr --help` which leads to an exception with stack trace:
```
Traceback (most recent call last):
  File "/home/pf/dev/hue-control/./huemgr", line 3, in <module>
    from huectl.bridge import HueBridge, HueBridgeSearch, HueDeviceScanResults
  File "/home/pf/dev/hue-control/huectl/bridge.py", line 10, in <module>
    from huectl.light import HueLight
  File "/home/pf/dev/hue-control/huectl/light.py", line 1, in <module>
    from huectl.ro import read_only_properties as read_only
ModuleNotFoundError: No module named 'huectl.ro'
```

**Comment by mechalas** [comment]
Fixed. Thanks.

I don't really like this implementation so that will probably go away in the near future.
